pub const Single = struct {
    media_type: i32,
    has_dash_audio: bool,
    is_completed: bool,
    total_bytes: i64,
    downloaded_bytes: i64,
    title: []const u8,
    type_tag: []const u8,
    cover: []const u8,
    video_quality: i32,
    prefered_video_quality: i32,
    guessed_total_bytes: i32,
    total_time_milli: i64,
    danmaku_count: i32,
    time_update_stamp: i64,
    time_create_stamp: i64,
    can_play_in_advance: bool,
    interrupt_transform_temp_file: bool,
    quality_pithy_description: []const u8,
    quality_superscript: []const u8,
    cache_version_code: i32,
    preferred_audio_quality: i32,
    audio_quality: i32,
    avid: i64,
    spid: i32,
    seasion_id: i32,
    bvid: []const u8,
    owner_id: i64,
    owner_name: []const u8,
    is_charge_video: bool,
    verification_code: i32,
    page_data: struct {
        cid: i64,
        page: i32,
        from: []const u8,
        part: []const u8,
        link: []const u8,
        rich_vid: []const u8,
        vid: []const u8,
        has_alias: bool,
        tid: i32,
        width: i32,
        height: i32,
        rotate: i32,
        download_title: []const u8,
        download_subtitle: []const u8,
    },
};

pub const Playlist = struct {
    media_type: i32,
    has_dash_audio: bool,
    is_completed: bool,
    total_bytes: i64,
    downloaded_bytes: i64,
    title: []const u8,
    type_tag: []const u8,
    cover: []const u8,
    video_quality: i32,
    prefered_video_quality: i32,
    guessed_total_bytes: i32,
    total_time_milli: i64,
    danmaku_count: i32,
    time_update_stamp: i64,
    time_create_stamp: i64,
    can_play_in_advance: bool,
    interrupt_transform_temp_file: bool,
    quality_pithy_description: []const u8,
    quality_superscript: []const u8,
    cache_version_code: i32,
    preferred_audio_quality: i32,
    audio_quality: i32,
    ep: struct {
        av_id: i64,
        page: i32,
        danmaku: i64,
        cover: []const u8,
        episode_id: i64,
        index: []const u8,
        index_title: []const u8,
        from: []const u8,
        season_type: i32,
        width: i32,
        height: i32,
        rotate: i32,
        link: []const u8,
        bvid: []const u8,
        sort_index: i64,
    },
    season_id: []const u8,
};
